# Grant OPA/kube-mgmt read-only access to resources. This lets kube-mgmt
# replicate resources into OPA so they can be used in policies.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.clusterRoleBinding.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRoleBinding.roleRef.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:{{ .Values.namespace }}
  apiGroup: rbac.authorization.k8s.io
