kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-config
  namespace: opa
data:
  opa-config.yaml: |
    services:
      dockerhub-registry:
        url: https://registry.hub.docker.com
        type: oci
    bundles:
      authz:
        service: dockerhub-registry
        resource: docker.io/leovice/opa-bundle-scheduling:latest
        persist: false
        polling:
          min_delay_seconds: 60
          max_delay_seconds: 120
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-env-config
  namespace: opa
data:
  SCHEDULER_URL: "http://ai-inference-server-mock.ai-inference-server-mock.svc.cluster.local:8080/scheduling"
