{{- if .Values.customRBAC.enabled }}
{{- range .Values.customRBAC.roles }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .name }}
rules:
{{- range .rules }}
- apiGroups: {{ toYaml .apiGroups | nindent 4 }}
  resources: {{ toYaml .resources | nindent 4 }}
  verbs: {{ toYaml .verbs | nindent 4 }}
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .name }}
roleRef:
  kind: ClusterRole
  name: {{ .name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:opa
  apiGroup: rbac.authorization.k8s.io

{{- end }}
{{- end }}
