apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.opaConfig.name }}
  namespace: {{ .Values.namespace }}
data:
  opa-config.yaml: |-
    services:
      {{- range $svcName, $svc := .Values.configMaps.opaConfig.data.services }}
      {{ $svcName }}:
        {{- range $key, $value := $svc }}
        {{ $key }}: {{ if or (eq $key "url") (eq $key "resource") }}{{ quote $value }}{{ else }}{{ $value }}{{ end }}
        {{- end }}
      {{- end }}
    bundles:
      {{- range $bundleName, $bundle := .Values.configMaps.opaConfig.data.bundles }}
      {{ $bundleName }}:
        {{- range $key, $value := $bundle }}
        {{- if eq $key "polling" }}
        polling:
          {{- range $pKey, $pValue := $value }}
          {{ $pKey }}: {{ $pValue }}
          {{- end }}
        {{- else }}
        {{ $key }}: {{ if eq $key "resource" }}{{ quote $value }}{{ else }}{{ $value }}{{ end }}
        {{- end }}
        {{- end }}
      {{- end }}