# Grant OPA/kube-mgmt role defined above.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.rbac.roleBinding.name }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.role.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:{{ .Values.namespace }}
  apiGroup: rbac.authorization.k8s.io
